{application,phoenix_client,
             [{applications,[kernel,stdlib,elixir,logger,ssl,
                             websocket_client]},
              {description,"Connect to Phoenix Channels from Elixir\n"},
              {modules,['Elixir.PhoenixClient','Elixir.PhoenixClient.Channel',
                        'Elixir.PhoenixClient.ChannelSupervisor',
                        'Elixir.PhoenixClient.Message',
                        'Elixir.PhoenixClient.Message.V1',
                        'Elixir.PhoenixClient.Message.V2',
                        'Elixir.PhoenixClient.Socket',
                        'Elixir.PhoenixClient.Transport',
                        'Elixir.PhoenixClient.Transports.Websocket']},
              {registered,[]},
              {vsn,"0.11.1"},
              {mod,{'Elixir.PhoenixClient',[]}}]}.
